//ACCOUNT
export const SET_GIVEN_OFFERS = "SET_GIVEN_OFFERS"
export const SET_RECEIVED_OFFERS = "SET_RECEIVED_OFFERS"

//NOTIFICATION
export const SET_NOTIFICATION = "SET_NOTIFICATION"
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION"