import { useEffect } from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'

//COMPONENTS
import CategoryList from '../src/components/CategoryList/CategoryList'
import Header from '../src/components/Header/Header'
import Main from '../src/components/MainHOC/Main'
import ProductList from '../src/components/ProductList/ProductList'
//COMPONENTS

import apiEndpoints from '../src/constants/apiEndpoints'


export default function Home({ products, categories }) {

  const router = useRouter();
  const { kategori } = router.query;

  useEffect(() => {
  }, [kategori])

  return (
    <>
      <Head>
        <title>İkinci El Project | Ali Aydemir</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main>
        <CategoryList categories={categories} />
        <ProductList products={products} />
      </Main>
    </>
  )
}

//DONE: Categoriler ve Ürünler serverside Props ile çekilecek
//TODO: Router ile gelen parametreye göre ürün listesi yükle ve kategori border ı stille
export async function getServerSideProps(context) {

  const products = await fetch(apiEndpoints.product.allProducts);
  const categories = await fetch(apiEndpoints.category.allCategories);


  return {
    props: {
      products: await products.json(),
      categories: await categories.json()
    }, // will be passed to the page component as props
  }
}