import Head from 'next/head'
import CategoryList from '../src/components/CategoryList/CategoryList'
import Header from '../src/components/Header/Header'
import Main from '../src/components/MainHOC/Main'
import { useRouter } from 'next/router'

export default function Home({ category = "/" }) {

  // const router = useRouter();
  // const { category } = router.query;
  console.log(category);

  return (
    <>
      <Head>
        <title>İkinci El Project | Ali Aydemir</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main>
        <CategoryList categories={[]} />
      </Main>
    </>
  )
}

//TODO: Categoriler ve Ürünler serverside Props ile çekilecek
